<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="workflow" nsURI="http://www.eclipse.org/efm/Workflow" nsPrefix="Workflow">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NamedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow" eSuperTypes="#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="manifest" lowerBound="1"
        eType="#//common/Manifest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workspace" eType="#//common/Workspace"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="director" upperBound="-1"
        eType="#//Director" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbexOption" eType="#//common/SymbexOption"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="console" eType="#//common/ConsoleLogFormat"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shellMode" eType="#//common/ShellMode"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developerTuning" eType="#//common/DeveloperTuningOption"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Director" eSuperTypes="#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="manifest" lowerBound="1"
        eType="#//common/Manifest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workflow" eType="#//Workflow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//common/Project"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supervisor" eType="#//SupervisorWorker"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="worker" upperBound="-1"
        eType="#//Worker" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="console" eType="#//common/ConsoleLogFormat"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developerTuning" eType="#//common/DeveloperTuningOption"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Worker" eSuperTypes="#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="manifest" lowerBound="1"
        eType="#//common/Manifest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="director" eType="#//Director"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="console" eType="#//common/ConsoleLogFormat"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupervisorWorker" eSuperTypes="#//Worker">
    <eStructuralFeatures xsi:type="ecore:EReference" name="limit" eType="#//common/GraphExplorationLimit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queue" eType="#//common/GraphExplorationQueue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extender" eType="#//common/TraceSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redundancy" eType="#//common/RedundancyDetection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageWorker" abstract="true" eSuperTypes="#//Worker">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" eType="#//common/TraceSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="normalizationEnabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimizationEnabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopWhenComplete" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="breakEnabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sliceWhenComplete" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heuristicEnabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#//common/CoverageScopeKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heuristicConfig" eType="#//common/CoverageHeuristic"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestWorker" abstract="true" eSuperTypes="#//Worker"/>
  <eClassifiers xsi:type="ecore:EClass" name="Serializer" abstract="true" eSuperTypes="#//Worker">
    <eStructuralFeatures xsi:type="ecore:EReference" name="format" eType="#//common/TraceSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CSS" eType="#//common/TraceSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" eType="#//common/TraceSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="folderName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledNormalization" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledNumerization" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledInitialValuesPrinting"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledLifelinesPrinting"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledModifiedDataSelection"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eSubpackages name="common" nsURI="http://www.eclipse.org/efm/Workflow/Common" nsPrefix="Common">
    <eClassifiers xsi:type="ecore:EEnum" name="AnalysisProfileKind">
      <eLiterals name="ANALYSIS_UNDEFINED_PROFILE" literal="ANALYSIS_UNDEFINED_PROFILE"/>
      <eLiterals name="ANALYSIS_EXPLORATION_PROFILE" value="1" literal="Exploration"/>
      <eLiterals name="ANALYSIS_TRANSITION_COVERAGE_PROFILE" value="2" literal="Transition Coverage"/>
      <eLiterals name="ANALYSIS_BEHAVIOR_SELECTION_PROFILE" value="3" literal="Behavior Selection"/>
      <eLiterals name="ANALYSIS_TEST_OFFLINE_PROFILE" value="4" literal="Test Offline"/>
      <eLiterals name="ANALYSIS_ACSL_GENERATION_PROFILE" value="5" literal="Inference"/>
      <eLiterals name="ANALYSIS_EXTRANEOUS_PROFILE" value="10" literal="Extra"/>
      <eLiterals name="ANALYSIS_USER_SEW_PROFILE" value="10" literal="ANALYSIS USER-SEW PROFILE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Workspace">
      <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//common/Location"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//common/Project"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Location">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="root" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="launch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="output"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="log" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="log"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="debug" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="debug"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Project">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="."/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="GraphExplorationStrategyKind">
      <eLiterals name="BEST_FIRST_SEARCH" literal="BEST_FIRST_SEARCH"/>
      <eLiterals name="BREADTH_FIRST_SEARCH" value="1" literal="BREADTH_FIRST_SEARCH"/>
      <eLiterals name="DEPTH_FIRST_SEARCH" value="2" literal="DEPTH_FIRST_SEARCH"/>
      <eLiterals name="RANDOM_FIRST_SEARCH" value="3" literal="RANDOM_FIRST_SEARCH"/>
      <eLiterals name="XFS" value="4"/>
      <eLiterals name="FIRST" value="5"/>
      <eLiterals name="LAST" value="6"/>
      <eLiterals name="ALL" value="7" literal="ALL"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GraphExplorationLimit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="eval" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="node" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="report" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="save" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GraphExplorationQueue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strategy" eType="#//common/GraphExplorationStrategyKind"
          defaultValueLiteral="BREADTH_FIRST_SEARCH"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="heuristicEnabled" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ConsoleVerbosityKind">
      <eLiterals name="UNDEFINED"/>
      <eLiterals name="SILENT" value="1" literal="SILENT"/>
      <eLiterals name="MINIMUM" value="2"/>
      <eLiterals name="MEDIUM" value="3"/>
      <eLiterals name="MAXIMUM" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConsoleLogFormat">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="report" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="verbosity" eType="#//common/ConsoleVerbosityKind"
          defaultValueLiteral="UNDEFINED"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="spiderInit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="spiderStep" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="spiderStop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TraceElementKind">
      <eLiterals name="UNDEFINED" literal="undefined"/>
      <eLiterals name="CONDITION" value="1" literal="condition"/>
      <eLiterals name="DECISION" value="2" literal="decision"/>
      <eLiterals name="FORMULA" value="3" literal="formula"/>
      <eLiterals name="PATH_CONDITION" value="4" literal="path#condition"/>
      <eLiterals name="PATH_CONDITION_LEAF" value="5" literal="path#condition#leaf"/>
      <eLiterals name="PATH_TIMED_CONDITION" value="6" literal="path#timed#condition"/>
      <eLiterals name="PATH_TIMED_CONDITION_LEAF" value="7" literal="path#timed#condition#leaf"/>
      <eLiterals name="NODE_CONDITION" value="8" literal="node#condition"/>
      <eLiterals name="NODE_CONDITION_LEAF" value="9" literal="node#condition#leaf"/>
      <eLiterals name="NODE_TIMED_CONDITION" value="10" literal="node#timed#condition"/>
      <eLiterals name="NODE_TIMED_CONDITION_LEAF" value="11" literal="node#timed#condition#leaf"/>
      <eLiterals name="ASSIGN" value="12" literal="assign"/>
      <eLiterals name="DELTA" value="13" literal="delta"/>
      <eLiterals name="TIME" value="14" literal="time"/>
      <eLiterals name="VARIABLE" value="15" literal="variable"/>
      <eLiterals name="NEWFRESH" value="16" literal="newfresh"/>
      <eLiterals name="COM" value="17" literal="com"/>
      <eLiterals name="INOUT" value="18" literal="inout"/>
      <eLiterals name="INPUT" value="19" literal="input"/>
      <eLiterals name="OUTPUT" value="20" literal="output"/>
      <eLiterals name="INPUT_ENV" value="21" literal="input#env"/>
      <eLiterals name="OUTPUT_ENV" value="22" literal="output#env"/>
      <eLiterals name="INPUT_RDV" value="23" literal="input#rdv"/>
      <eLiterals name="OUTPUT_RDV" value="24" literal="output#rdv"/>
      <eLiterals name="INPUT_BUFFER" value="25" literal="input#buffer"/>
      <eLiterals name="OUTPUT_BUFFER" value="26" literal="output#buffer"/>
      <eLiterals name="INPUT_VAR" value="27" literal="input#var"/>
      <eLiterals name="OUTPUT_VAR" value="28" literal="output#var"/>
      <eLiterals name="PORT" value="29" literal="port"/>
      <eLiterals name="SIGNAL" value="30" literal="signal"/>
      <eLiterals name="MESSAGE" value="31" literal="message"/>
      <eLiterals name="CHANNEL" value="32" literal="channel"/>
      <eLiterals name="BUFFER" value="33" literal="buffer"/>
      <eLiterals name="RUNNABLE" value="34" literal="runnable"/>
      <eLiterals name="ROUTINE" value="35" literal="routine"/>
      <eLiterals name="TRANSITION" value="36" literal="transition"/>
      <eLiterals name="STATE" value="37" literal="state"/>
      <eLiterals name="STATEMACHINE" value="38" literal="statemachine"/>
      <eLiterals name="MODEL_MACHINE" value="39" literal="model"/>
      <eLiterals name="PROTOTYPE_MACHINE" value="40" literal="prototype"/>
      <eLiterals name="INSTANCE_MACHINE" value="41" literal="instance"/>
      <eLiterals name="MACHINE" value="42" literal="machine"/>
      <eLiterals name="SYSTEM" value="43" literal="system"/>
      <eLiterals name="FILE_HEADER" value="50" literal="file#header"/>
      <eLiterals name="FILE_BEGIN" value="51" literal="file#begin"/>
      <eLiterals name="FILE_END" value="52" literal="file#end"/>
      <eLiterals name="TESTCASE_HEADER" value="53" literal="testcase#header"/>
      <eLiterals name="TESTCASE_BEGIN" value="54" literal="testcase#begin"/>
      <eLiterals name="TESTCASE_END" value="55" literal="testcase#end"/>
      <eLiterals name="INIT_HEADER" value="56" literal="init#header"/>
      <eLiterals name="INIT_BEGIN" value="57" literal="init#begin"/>
      <eLiterals name="INIT_END" value="58" literal="init#end"/>
      <eLiterals name="STEP_HEADER" value="59" literal="step#header"/>
      <eLiterals name="STEP_BEGIN" value="60" literal="step#begin"/>
      <eLiterals name="STEP_END" value="61" literal="step#end"/>
      <eLiterals name="COMMENT" value="62" literal="comment"/>
      <eLiterals name="SEPARATOR" value="63" literal="separator"/>
      <eLiterals name="NEWLINE" value="64" literal="newline"/>
      <eLiterals name="NEXT" value="65" literal="next"/>
      <eLiterals name="LIFELINE" value="66" literal="lifeline"/>
      <eLiterals name="LIFELINE_HEADER" value="67" literal="lifeline#header"/>
      <eLiterals name="LIFELINE_BEGIN" value="68" literal="lifeline#begin"/>
      <eLiterals name="LIFELINE_END" value="69" literal="lifeline#end"/>
      <eLiterals name="LIFELINE_ID" value="70" literal="lifeline#id"/>
      <eLiterals name="LIFELINE_STATE" value="71" literal="lifeline#state"/>
      <eLiterals name="RAW_ATTRIBUTE" value="72" literal="__raw__"/>
      <eLiterals name="EXECUTION_CONTEXT_ID" value="80" literal="execution#context#id"/>
      <eLiterals name="NODE" value="81" literal="node"/>
      <eLiterals name="NODE_LABEL" value="82" literal="node#label"/>
      <eLiterals name="NODE_HEADER" value="83" literal="node#header"/>
      <eLiterals name="NODE_DATA" value="84" literal="node#data"/>
      <eLiterals name="NODE_INFO" value="85" literal="node#info"/>
      <eLiterals name="NODE_TRACE_RUN" value="86" literal="node#trace#run"/>
      <eLiterals name="NODE_TRACE_IO" value="87" literal="node#trace#io"/>
      <eLiterals name="VALUE_PARAMETER_BEGIN" value="88" literal="value#parameter#begin"/>
      <eLiterals name="VALUE_PARAMETER_SEPARATOR" value="89" literal="value#parameter#separator"/>
      <eLiterals name="VALUE_PARAMETER_END" value="90" literal="value#parameter#end"/>
      <eLiterals name="VALUE_ARRAY_BEGIN" value="91" literal="value#array#begin"/>
      <eLiterals name="VALUE_ARRAY_SEPARATOR" value="92" literal="value#array#separator"/>
      <eLiterals name="VALUE_ARRAY_END" value="93" literal="value#array#end"/>
      <eLiterals name="VALUE_STRUCT_BEGIN" value="94" literal="value#struct#begin"/>
      <eLiterals name="VALUE_STRUCT_SEPARATOR" value="95" literal="value#struct#separator"/>
      <eLiterals name="VALUE_STRUCT_END" value="96" literal="value#struct#end"/>
      <eLiterals name="META_TRACE" value="97" literal="trace"/>
      <eLiterals name="META_DEBUG" value="98" literal="debug"/>
      <eLiterals name="TIPS" value="99" literal="tips"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TraceElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" eType="#//common/TraceElementKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TraceSpecification" eSuperTypes="#//NamedObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
          eType="#//common/TraceElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Manifest">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoconf" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="autostart" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SolverKind">
      <eLiterals name="CVC4" literal="CVC4"/>
      <eLiterals name="Z3" value="1" literal="Z3"/>
      <eLiterals name="YICES2" value="2" literal="YICES2"/>
      <eLiterals name="OMEGA" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SymbexOption"/>
    <eClassifiers xsi:type="ecore:EClass" name="ShellMode" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="&quot;stop.symbex&quot;"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="HeuristicClassKind">
      <eLiterals name="BASIC"/>
      <eLiterals name="NAIVE" value="1" literal="NAIVE"/>
      <eLiterals name="SMART" value="2"/>
      <eLiterals name="AGRESSIVE" value="3" literal="AGRESSIVE"/>
      <eLiterals name="NOTHING_ELSE" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CoverageHeuristic">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="heuristicTrials" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectiveRateGoal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectiveRestGoal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="heuristicStart" eType="#//common/HeuristicClassKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directiveTraceCount"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directiveTraceSize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directiveTraceHeuristic"
          eType="#//common/HeuristicClassKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lookaheadDepth" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lookaheadWidth" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitStronglyRandomEnabled"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitStronglyCount" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitWeaklyRandomEnabled"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitWeaklyCount" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitOtherRandomEnabled"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitOtherCount" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CoverageScopeKind">
      <eLiterals name="MODEL" literal="MODEL"/>
      <eLiterals name="INSTANCE" value="1" literal="INSTANCE"/>
      <eLiterals name="DETAILS" value="2" literal="DETAILS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CheckingScopeKind">
      <eLiterals name="GLOBALLY" literal="GLOBALLY"/>
      <eLiterals name="LOCALLY" value="1" literal="LOCALLY"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeveloperTuningOption">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="logTraceFilename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="debugTraceFilename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="debugLevel" eType="#//common/DebuglevelKind"
          defaultValueLiteral="ZERO"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="debugFilename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputFilename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specificationFilename"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="executableFilename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initializationFilename"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbexGraphFilename"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parsedModelFilename"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="compiledModelFilename"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbexTraceFilename"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledParsing" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledConfiguring" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledCompiling" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledLoading" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledComputing" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledReporting" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledSolving" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledProfiling" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledAllProcessStage"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledPreProcessing"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledPostProcessing"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledProcessing" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledPreFiltering"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledPostFiltering"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledFiltering" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledQueue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledProgram" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledStatement" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledStatementAssignment"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledStatementCommunication"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledStatementTestDecision"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledBytecode" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledData" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledTrace" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledVariable" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledBuffer" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledPort" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledSignal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledConnexion" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledTime" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledExecutable" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledActivity" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledRoutine" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledTransition" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledMachine" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledStatemachine"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledNameId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledQualifiedNameId"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledFullyQualifiedNameId"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledRedundance" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledReferenceCounting"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledNothing" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledGodMode" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DebuglevelKind">
      <eLiterals name="NONE" value="-1"/>
      <eLiterals name="ZERO" literal="ZERO"/>
      <eLiterals name="LOW" value="1" literal="LOW"/>
      <eLiterals name="MEDIUM" value="2" literal="MEDIUM"/>
      <eLiterals name="HIGH" value="3" literal="HIGH"/>
      <eLiterals name="ULTRA" value="4"/>
      <eLiterals name="GOD_MODE" value="5" literal="GOD_MODE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="RedundancyPathScope">
      <eLiterals name="ALL" literal="ALL"/>
      <eLiterals name="CURRENT" value="1" literal="CURRENT"/>
      <eLiterals name="PARENT" value="2" literal="PARENT"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="RedundancyComparerOperation">
      <eLiterals name="INCLUSION" literal="INCLUSION"/>
      <eLiterals name="EQUALITY" value="1" literal="EQUALITY"/>
      <eLiterals name="SYNTAXIC_EQUALITY" value="2" literal="SYNTAXIC_EQUALITY"/>
      <eLiterals name="ALPHA_EQUIVALENCE" value="3" literal="ALPHA_EQUIVALENCE"/>
      <eLiterals name="TRIVIALLY_EQUALITY" value="4"/>
      <eLiterals name="CONTROL_STATE" value="5" literal="CONTROL_STATE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RedundancyDetection">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledDetetction" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathScope" eType="#//common/RedundancyPathScope"
          defaultValueLiteral="CURRENT"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparerOperation" eType="#//common/RedundancyComparerOperation"
          defaultValueLiteral="INCLUSION"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="solverChoice" eType="#//common/SolverKind"
          defaultValueLiteral="OMEGA"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataScope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="ALL"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledTrivialLoopDetetction"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="coverage" nsURI="http://www.eclipse.org/efm/Workflow/Coverage"
      nsPrefix="Coverage">
    <eClassifiers xsi:type="ecore:EClass" name="TransitionCoverageWorker" eSuperTypes="#//CoverageWorker"/>
    <eClassifiers xsi:type="ecore:EClass" name="InputOutputCoverageWorker" eSuperTypes="#//CoverageWorker"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionCoverageWorker" eSuperTypes="#//CoverageWorker"/>
    <eClassifiers xsi:type="ecore:EClass" name="DecisionCoverageWorker" eSuperTypes="#//CoverageWorker"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionDecisionCoverageWorker" eSuperTypes="#//CoverageWorker"/>
    <eClassifiers xsi:type="ecore:EClass" name="ModifiedConditionDecisionCoverageWorker"
        eSuperTypes="#//CoverageWorker"/>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorCoverageWorker" eSuperTypes="#//CoverageWorker">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkingScope" eType="#//common/CheckingScopeKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderedTrace" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitConsecutive" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitFolding" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitLucky" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitMax" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitFinal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jumpHeight" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jumpTrialsLimit" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitCount" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jumpCount" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jumpSlice" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="#//common/TraceSpecification"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="extraneous" nsURI="http://www.eclipse.org/efm/Workflow/Extraneous"
      nsPrefix="Extraneous">
    <eClassifiers xsi:type="ecore:EClass" name="ExtraneousWorker" abstract="true"
        eSuperTypes="#//Worker">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraSEW" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="AnalysisProfileRequired"
          upperBound="-1" eType="#//common/AnalysisProfileKind" defaultValueLiteral="Exploration"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="test" nsURI="http://www.eclipse.org/efm/Workflow/Test" nsPrefix="Test">
    <eClassifiers xsi:type="ecore:EClass" name="OfflineTestWorker" eSuperTypes="#//Worker">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mergedTraceFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testPurposeFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="observable" eType="#//common/TraceSpecification"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="controllable" eType="#//common/TraceSpecification"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="serializer" nsURI="http://www.eclipse.org/efm/Workflow/Serializer"
      nsPrefix="Serializer">
    <eClassifiers xsi:type="ecore:EClass" name="ModelGraphicSerializerWorker" eSuperTypes="#//Serializer"/>
    <eClassifiers xsi:type="ecore:EClass" name="ModelGraphvizSerializerWorker" eSuperTypes="#//Serializer"/>
    <eClassifiers xsi:type="ecore:EClass" name="SymbexGraphicSerializerWorker" eSuperTypes="#//Serializer"/>
    <eClassifiers xsi:type="ecore:EClass" name="SymbexGraphVizSerializerWorker" eSuperTypes="#//Serializer"/>
    <eClassifiers xsi:type="ecore:EClass" name="BasicTraceSerializer" eSuperTypes="#//Serializer"/>
    <eClassifiers xsi:type="ecore:EClass" name="TTCNTraceSerializer" eSuperTypes="#//Serializer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledCustomization"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledAdapters" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlModuleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="declarationsModuleName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="templatesModuleName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testcasesModuleName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testcasesStartingWrapper"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testcasesEndingWrapper"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testcasesSendingWrapper"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testcasesReceivingWrapper"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaptationModuleName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaptationUtilsImpl"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaptationStartingEndingImpl"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaptationSendingImpl"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaptationReceivingImpl"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SymbexSequenceDiagramSerializerWorker"
        eSuperTypes="#//Serializer"/>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceDiagramTraceSerializer" eSuperTypes="#//Serializer"/>
  </eSubpackages>
</ecore:EPackage>
