<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="expression" nsURI="http://www.eclipse.org/efm/SEW/Expression"
    nsPrefix="expression">
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="sew.ecore#//WValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" upperBound="-1"
        eType="ecore:EClass sew.ecore#//WValueSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExpressionValue" eSuperTypes="sew.ecore#//WValueSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralArrayValue" eSuperTypes="#//LiteralExpressionValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="ecore:EClass sew.ecore#//WValueSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralIntegerValue" eSuperTypes="#//LiteralExpressionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralBooleanValue" eSuperTypes="#//LiteralExpressionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralCharacterValue" eSuperTypes="#//LiteralExpressionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralRationalValue" eSuperTypes="#//LiteralExpressionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numerator" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="denominator" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralStringValue" eSuperTypes="#//LiteralExpressionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralNullValue" eSuperTypes="#//LiteralExpressionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralFloatValue" eSuperTypes="#//LiteralExpressionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralRealValue" eSuperTypes="#//LiteralExpressionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralReferenceValue" eSuperTypes="#//LiteralExpressionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralObjectReference" eSuperTypes="#//LiteralReferenceValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass sew.ecore#//WObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralThisInstance" eSuperTypes="#//LiteralReferenceValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralSelfInstance" eSuperTypes="#//LiteralReferenceValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralParentInstance" eSuperTypes="#//LiteralReferenceValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralSuperInstance" eSuperTypes="#//LiteralReferenceValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralSystemInstance" eSuperTypes="#//LiteralReferenceValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralEnvInstance" eSuperTypes="#//LiteralReferenceValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralTimeVariable" eSuperTypes="#//LiteralReferenceValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralTimeDeltaVariable" eSuperTypes="#//LiteralReferenceValue"/>
</ecore:EPackage>
